# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.disable_button.showUpdateHistory", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1360838867);
user_pref("app.update.lastUpdateTime.background-update-timer", 1360832221);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1360838987);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1361433822);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1361433702);
user_pref("app.update.service.enabled", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.migration.version", 8);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.buildID", "20130201065344");
user_pref("browser.startup.homepage_override.mstone", "18.0.2");
user_pref("browser.syncPromoViewsLeft", 2);
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("capability.policy.maonoscript.javascript.enabled", "allAccess");
user_pref("capability.policy.maonoscript.sites", "emt.ee telia.no telia.se teliasonera.net about: about:addons about:blank about:blocked about:certerror about:config about:crashes about:home about:memory about:neterror about:plugins about:privatebrowsing about:sessionrestore about:support blob: chrome: http://emt.ee http://telia.no http://telia.se http://teliasonera.net https://emt.ee https://telia.no https://telia.se https://teliasonera.net resource:");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"check-compatibility@dactyl.googlecode.com\":{\"version\":\"1.3\",\"type\":\"extension\",\"descriptor\":\"C:\\\\TS_Test_Automation_PoC\\\\Browsers\\\\FF_Profile\\\\t43yqj7d.FF_Profile\\\\extensions\\\\check-compatibility@dactyl.googlecode.com.xpi\"},\"firebug@software.joehewitt.com\":{\"version\":\"1.11.1\",\"type\":\"extension\",\"descriptor\":\"C:\\\\TS_Test_Automation_PoC\\\\Browsers\\\\FF_Profile\\\\t43yqj7d.FF_Profile\\\\extensions\\\\firebug@software.joehewitt.com.xpi\"}}");
user_pref("extensions.check-compatibility.app-version", "18.0.2");
user_pref("extensions.check-compatibility.saved.18.0", true);
user_pref("extensions.check-compatibility.saved.nightly", true);
user_pref("extensions.checkCompatibility.18.0", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B7eb3f691-25b4-4a85-9038-9e57e2bcd537%7D:0.4.4,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:18.0.2");
user_pref("extensions.firebug.addonBarOpened", true);
user_pref("extensions.firebug.currentVersion", "1.11.1");
user_pref("extensions.firebug.previousPlacement", 3);
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\HP\\\\Unified Functional Testing\\\\\\\\bin\\\\Mozilla\\\\Common\",\"mtime\":1356093221097}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1360311357353}}},{\"name\":\"winreg-app-user\",\"addons\":{\"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\HP\\\\Unified Functional Testing\\\\Bin\\\\Mozilla\\\\Common\",\"mtime\":1356093221097}}},{\"name\":\"app-profile\",\"addons\":{\"check-compatibility@dactyl.googlecode.com\":{\"descriptor\":\"C:\\\\TS_Test_Automation_PoC\\\\Browsers\\\\FF_Profile\\\\t43yqj7d.FF_Profile\\\\extensions\\\\check-compatibility@dactyl.googlecode.com.xpi\",\"mtime\":1360829754208},\"firebug@software.joehewitt.com\":{\"descriptor\":\"C:\\\\TS_Test_Automation_PoC\\\\Browsers\\\\FF_Profile\\\\t43yqj7d.FF_Profile\\\\extensions\\\\firebug@software.joehewitt.com.xpi\",\"mtime\":1361283041106},\"{7eb3f691-25b4-4a85-9038-9e57e2bcd537}\":{\"descriptor\":\"C:\\\\TS_Test_Automation_PoC\\\\Browsers\\\\FF_Profile\\\\t43yqj7d.FF_Profile\\\\extensions\\\\{7eb3f691-25b4-4a85-9038-9e57e2bcd537}.xpi\",\"mtime\":1359028890649}}}]");
user_pref("extensions.lastAppVersion", "18.0.2");
user_pref("extensions.lastPlatformVersion", "18.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("gecko.buildID", "20130201065344");
user_pref("gecko.mstone", "18.0.2");
user_pref("general.warnOnAboutConfig", false);
user_pref("gfx.direct3d.prefer_10_1", true);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("noscript.ABE.migration", 1);
user_pref("noscript.gtemp", "");
user_pref("noscript.notify", false);
user_pref("noscript.options.tabSelectedIndexes", "1,0,0");
user_pref("noscript.policynames", "");
user_pref("noscript.subscription.lastCheck", -576294774);
user_pref("noscript.temp", "");
user_pref("noscript.untrusted", "");
user_pref("noscript.version", "2.6.4.4");
user_pref("noscript.visibleUIChecked", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugins.hide_infobar_for_missing_plugin", true);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("toolkit.startup.last_success", 1361433581);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("toolkit.telemetry.rejected", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1363954457);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
